name: Deploy to App Engine

on:
  push:
    branches:
      - dev  # Change to your target deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'  # Use 'latest' or a specific version

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy to App Engine
      run: |
        gcloud app deploy app.yaml --quiet
